export const peliculas = [
    {
        id: 1,
        titulo: "Los 4 Fantásticos: Primeros Pasos",
        genero: "Acción",
        duracion: "1h 55min",
        clasificacion: "APT",
        rating: 4,
        imagenPoster: "https://www.lahiguera.net/cinemania/pelicula/11532/los_4_fantasticos_primeros_pasos-cartel-12494.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11532/los_4_fantasticos_primeros_pasos_54772.jpg",
        trailerUrl: "https://youtu.be/waf9snfaUFw",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "Cuatro jóvenes científicos obtienen habilidades extraordinarias tras un experimento que sale mal. Mientras aprenden a trabajar como equipo, deberán enfrentar una amenaza que podría destruir su mundo y todo lo que conocen.",
        director: "Matt Shakman",
        reparto: "Pedro Pascal, Vanessa Kirby, Joseph Quinn, Ebon Moss-Bachrach",
        estreno: true
    },

    {
        id: 2,
        titulo: "Los Tipos Malos 2",
        genero: "Animación",
        duracion: "1h 44min",
        clasificacion: "APT",
        rating: 1,
        imagenPoster: "https://www.lahiguera.net/cinemania/pelicula/11552/los_tipos_malos_2-cartel-12621.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11552/los_tipos_malos_2_54601.jpg",
        trailerUrl: "https://youtu.be/8i8KXqdpP98",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "La banda de villanos reformados deberá enfrentar una nueva amenaza que pondrá a prueba su amistad y su compromiso por convertirse en héroes verdaderos.",
        director: "Pierre Perifel",
        reparto: "Sam Rockwell, Marc Maron, Awkwafina, Craig Robinson",
        estreno: false
    },
    {
        id: 3,
        titulo: "Otro Viernes de Locos",
        genero: "Familiar",
        duracion: "1h 51min",
        clasificacion: "APT",
        rating: 3,
        imagenPoster: "https://www.uvk.pe/images/movie/1753196641.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11276/ponte_en_mi_lugar_de_nuevo_54909.jpg",
        trailerUrl: "https://youtu.be/97ExuMBIE8Y",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "Una madre y su hija intercambian cuerpos inesperadamente y deberán aprender a vivir la vida de la otra, enfrentando retos cómicos y emocionales mientras buscan revertir el cambio.",
        director: "Nisha Ganatra",
        reparto: "Lindsay Lohan, Jamie Lee Curtis, Julia Butters",
        estreno: false
    },
    {
        titulo: "Superman",
        genero: "Acción",
        duracion: "2h 10min",
        clasificacion: "+14",
        rating: 5,
        imagenPoster: "https://www.lahiguera.net/cinemania/pelicula/11587/superman-cartel-12509.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11587/superman_55027.jpg",
        trailerUrl: "https://youtu.be/0X_kBulSMjQ",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "Clark Kent, uno de los últimos miembros de una raza extraterrestre extinta, se ve obligado a revelar sus poderes cuando la Tierra se ve invadida por un ejército de supervivientes que amenazan con destruir el planeta.",
        director: "James Gunn",
        reparto: "David Corenswet, Rachel Brosnahan, Nicholas Hoult, Edi Gathegi",
        estreno: true
    },
    {
        id: 5,
        titulo: "Amores Materialistas",
        genero: "Romance",
        duracion: "1h 57min",
        clasificacion: "+14",
        rating: 4,
        imagenPoster: "https://www.lahiguera.net/cinemania/pelicula/11734/materialistas-cartel-12508.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11734/materialistas_55237.jpg",
        trailerUrl: "https://youtu.be/jJyMcGr6t18",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "Lucy, una casamentera de gran éxito en Nueva York, ve tambalearse su vida personal y profesional cuando se ve atrapada en un triángulo amoroso entre un millonario carismático y su exnovio, un actor con dificultades económicas.",
        director: "Celine Song",
        reparto: "Dakota Johnson, Pedro Pascal, Chris Evans",
        estreno: true
    },

    {
        id: 6,
        titulo: "Como Entrenar a Tu Dragón",
        genero: "Familiar",
        duracion: "2h 5min",
        clasificacion: "APT",
        rating: 4,
        imagenPoster: "https://www.lahiguera.net/cinemania/pelicula/11551/como_entrenar_a_tu_dragon-cartel-12339.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11551/como_entrenar_a_tu_dragon_54835.jpg",
        trailerUrl: "https://youtu.be/Ns6ZEpQ1xS0",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "Un joven vikingo desafía las tradiciones de su pueblo cuando descubre que los dragones no son enemigos, sino criaturas extraordinarias capaces de crear vínculos profundos con los humanos.",
        director: "Dean DeBlois",
        reparto: "Jay Baruchel, America Ferrera, Gerard Butler",
        estreno: true
    },
    {
        id: 7,
        titulo: "La Hora de la Desaparición",
        genero: "Terror",
        duracion: "2h 8min",
        clasificacion: "+14",
        rating: 3,
        imagenPoster: "https://www.lahiguera.net/cinemania/pelicula/11772/weapons-cartel-12498.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11772/weapons_55030.jpg",
        trailerUrl: "https://youtu.be/J3R3DyQZ1e8",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "En un pequeño pueblo, varias personas comienzan a desaparecer misteriosamente a la misma hora cada noche. Un periodista investiga el origen del fenómeno, descubriendo una entidad que se alimenta del miedo.",
        director: "Bryce McGuire",
        reparto: "Timothée Chalamet, Anya Taylor-Joy, Toni Collette",
        estreno: false
    },
    {
        id: 8,
        titulo: "Jurassic World Renace",
        genero: "Acción",
        duracion: "2h 14min",
        clasificacion: "+14",
        rating: 1,
        imagenPoster: "https://www.lahiguera.net/cinemania/pelicula/11374/jurassic_world_el_renacer-cartel-12576.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11374/jurassic_world_el_renacer_54851.jpg",
        trailerUrl: "https://youtu.be/1R3LTANp7hw",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "Nuevas especies de dinosaurios modificados genéticamente escapan de un laboratorio secreto, obligando a un grupo de científicos y exploradores a evitar que la humanidad sea superada por las criaturas prehistóricas.",
        director: "Colin Trevorrow",
        reparto: "Chris Pratt, Bryce Dallas Howard, Isabella Sermon",
        estreno: false
    },
    {
        id: 9,
        titulo: "Lilo y Stitch",
        genero: "Familiar",
        duracion: "1h 40min",
        clasificacion: "APT",
        rating: 2,
        imagenPoster: "https://www.lahiguera.net/cinemania/pelicula/11368/lilo_y_stitch-cartel-12500.jpg",
        imagenTrailer: "https://www.lahiguera.net/cinemania/pelicula/11368/lilo_y_stitch_54899.jpg",
        trailerUrl: "https://youtu.be/9JIyINjMfcc",
        trailer: "TEASER TRÁILER OFICIAL",
        sinopsis: "Una niña solitaria en Hawái adopta por error a un experimento alienígena buscado en toda la galaxia. Juntos aprenderán el valor de la familia, la amistad y la aceptación.",
        director: "Chris Sanders",
        reparto: "Daveigh Chase, Chris Sanders, Tia Carrere",
        estreno: false
    }
];
